name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Zig Version
        run: zig version

      - name: Check Formatting
        run: zig fmt --check src/

      - name: Build (Debug)
        run: zig build

      - name: Build (Release)
        run: zig build -Doptimize=ReleaseSafe

      - name: Run Tests
        run: zig build test

      - name: Build Documentation
        run: zig build docs || true
