name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4

      - name: Zig Version
        run: zig version

      - name: Format Check
        run: zig fmt --check src/

      - name: Build
        run: zig build -Doptimize=ReleaseSafe

      - name: Test
        run: zig build test
